name: Taxonomy build

on:
  workflow_dispatch:
    inputs:
      branch:
        description: branch name to deploy (from _this_ repo)
        default: main
        required: true
      repository:
        description: repository name which triggered this event (taxonomy)
        required: true
      artifact_url:
        description: URL where the new (zipped) taxonomypackage lives
        required: true
      message:
        required: false
        default: "Remotely triggerd"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout self
        uses: actions/checkout@v4
      - run: |
          echo ${{ GITHUB_ACTOR }} Started an integration run.
          echo They pushed to ${{ github.event.client_payload.repository }}
      - run: |
          echo ${{ github.event.client_payload.artifact_url }}
          echo ${{ github.event.client_payload.repository }}

