name: Taxonomy build

on:
  workflow_dispatch:
    inputs:
      branch:
        description: branch name to deploy (from _this_ repo)
        default: main
        required: true
      repository:
        description: repository name which triggered this event (taxonomy)
        required: true
      artifact_name:
        description: Name of the artifact in this repo  (zipped taxonomypackage)
        required: true
      message:
        required: false
        default: "Remotely triggerd"
      run_id:
        required: true
        description: To download the artifact we need a run_id

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout self
        uses: actions/checkout@v4
      - run: |
          echo ${{ github.actor }} Started an integration run.
          echo They pushed to ${{ github.event.inputs.repository }}
      - run: |
          echo ${{ github.event.inputs.artifact_name }}
          echo ${{ github.event.inputs.branch }}
          echo the message is: ${{ github.event.inputs.message }}
          echo run-id: ${{ github.event.inputs.run-id }}
      - name: Downloaad new artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.event.inputs.artifact_name }}
          github-token: ${{ secrets.PAT }}
          run-id: ${{ github.event.inputs.run_id }}
          repository: ${{ github.event.repository }}
          path: public/${{ github.event.inputs.branch }}
      - run: |
          ls -l public

